services:
  #  #FRONT END
  #  frontend:
  #    build:
  #      context: ./backend/frontend/bluebid-react
  #      dockerfile: Dockerfile
  #    ports:
  #      - "3000:80" #using localhost 3000. nginx listens on 80 by default
  #    container_name: react-frontend
  #    restart: always
  #
  #  ## KAFKA
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # we are just making a POC so no need for replications
      KAFKA_MIN_INSYNC_REPLICAS: 1 # see above
    ports:
      - "9092:9092"
    networks:
      - kafka-net

  ## GATEWAY
  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    depends_on:
#      - user-service
      - catalog-service
      - file-upload-service
    environment:
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "8080:8080" # expose to host
    networks:
      - backend-net

#  # USER SERVICE
#  user-service:
#    build:
#      context: ./backend/user-service
#      dockerfile: Dockerfile
#    depends_on:
#      - user-db
#    environment:
#      #      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
#      #      JWT_SECRET: ${JWT_SECRET}
#      #      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
#      #      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
#      MONGO_PASSWORD: ${MONGO_PASSWORD}
#    networks:
#      - backend-net
#  #      - kafka-net
#
#  user-db:
#    image: postgres:15-alpine
#    restart: always
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
#      POSTGRES_USER: ${USER_DB_USER}
#      POSTGRES_DB: userdb
#    volumes:
#      - user-db:/var/lib/postgresql/data
#      - ./backend/init/init-userdb.sql:/docker-entrypoint-initdb.d/init-userdb.sql:ro
#    networks:
#      - backend-net

  # CATALOG SERVICE
  catalog-service:
    build:
      context: ./backend/catalog-service
      dockerfile: Dockerfile
    depends_on:
      - catalog-db
    environment:
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_USER: ${CATALOG_DB_USER}
    networks:
      - backend-net
      - kafka-net

  catalog-cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - catalog-cache:/data/cache

  catalog-db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_DB: catalogdb
    volumes:
      - catalog-db:/var/lib/postgresql/data
      #      - /home/katyaflix2/data/catalog-data:/var/lib/postgresql/data
      - ./backend/init/init-catalogdb.sql:/docker-entrypoint-initdb.d/init-catalogdb.sql:ro
    networks:
      - backend-net

  # file upload SERVICE
  file-upload-service:
    build:
      context: ./backend/file-upload-service
      dockerfile: Dockerfile
    depends_on:
      - file-upload-db
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
      MONGO_PASSWORD: ${FILE_UPLOAD_DB_PASSWORD}
      MONGO_USER: ${FILE_UPLOAD_DB_USER}
      MEDIA_ROOT: /app/katyaflix_data
    volumes:
      - "${MEDIA_ROOT}:/app/katyaflix_data"
    networks:
      - backend-net
      - kafka-net
    dns:
      - 8.8.8.8 # manually set DNS because Docker's default DNS sucks
      - 1.1.1.1

  file-upload-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${FILE_UPLOAD_DB_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${FILE_UPLOAD_DB_USER}
      MONGO_INITDB_DATABASE: fileuploaddb

    ports:
      - "27017:27017"
    volumes:
      - file-upload-db:/data/db
      #      - /home/katyaflix2/data/file-upload-data:/var/lib/postgresql/data
#      - ./backend/init/init-fileuploaddb.sql:/docker-entrypoint-initdb.d/init-fileuploaddb.sql:ro
    networks:
      - backend-net

  media-server:
    image: nginx:alpine
    container_name: katyaflix-media
    restart: unless-stopped
    depends_on:
      - file-upload-service
    ports:
      - "8081:80"
    volumes:
      - "${MEDIA_ROOT}/library:/library:ro"
      - "./nginx/media.conf:/etc/nginx/conf.d/default.conf:ro"

networks:
  backend-net:
    driver: bridge
  kafka-net:
    driver: bridge

volumes:
  user-db:
  catalog-db:
  file-upload-db:
  catalog-cache:
