spring.application.name=file-upload-service

spring.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@file-upload-db:27017/fileuploaddb?authSource=admin
spring.mongodb.database=fileuploaddb
media.root=${MEDIA_ROOT}
spring.mongodb.representation.uuid=standard

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=20GB

# Maximum size allowed for total multipart/form-data requests
spring.servlet.multipart.max-request-size=20GB