server {
    listen 80;

    server_name _;

    # Movie media
    location /media/movies/ {
        alias /library/media/movies/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Show media
    location /media/shows/ {
        alias /library/media/shows/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Movie assets
    location /assets/movies/ {
        alias /library/assets/movies/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Show assets
    location /assets/shows/ {
        alias /library/assets/shows/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Everything else is inaccessible
    location / {
        return 404;
    }
}