server {
    listen 80;

    server_name _;
    include /etc/nginx/mime.types;

    types {
        text/vtt vtt;
    }

    #Profile assets
    location /profile/assets/ {
        alias /library/profile/assets/;

        add_header Cache-Control "public, max-age=86400";
    }

    # # Movie media
    # location /media/movies/ {
    #     alias /library/media/movies/;

    #     add_header Cache-Control "public, max-age=86400";
    # }

    # # Show media
    # location /media/shows/ {
    #     alias /library/media/shows/;

    #     add_header Cache-Control "public, max-age=86400";
    # }

    location /media/movies/ {
        alias /library/media/movies/;

        add_header Cache-Control "public, max-age=86400";
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Range, Content-Type' always;
    }

    location /media/shows/ {
        alias /library/media/shows/;

        add_header Cache-Control "public, max-age=86400";
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Range, Content-Type' always;
    }

    # Movie assets
    location /assets/movies/ {
        alias /library/assets/movies/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Show assets
    location /assets/shows/ {
        alias /library/assets/shows/;

        add_header Cache-Control "public, max-age=86400";
    }

    # Everything else is inaccessible
    location / {
        return 404;
    }
}